### PR TITLE
MS-1160 task: incoporate change links on CYA page

### PR DESCRIPTION
**Pull request by jjrobothamho**
- update backlinks and next steps
- Reinstate CYA change links on page

### CODE REVIEW

**Comment by sulthan-ahmed** [comment]
there is a lot of custom in the `page-custom-back-links.js` that could possibly be refactored to be reusable.  I guess for now we might need to allow this because of time but it would be good to sit down with you and a whiteboard to understand the problem, common behaviour and then see if we can create a function

**Comment by jjrobothamho** [comment]
Yeah it's similar to the refactoring we needed to do with the data retention ticket.

**Comment by sulthan-ahmed** [comment]
Have you tested for the different scanarios?

**Comment by jjrobothamho** [comment]
I have tested the core three journey's but will confirm the others today.

**Comment by jjrobothamho** [comment]
All journey's tested and confirmed as working

**Comment by jjrobothamho** [comment]
Cheers

**Pull request merged**
