### PR TITLE
MS-1160 task: incorporate change links on CYA page

### PR DESCRIPTION
**Pull request by jjrobothamho**
- Reinstate change links on CYA page

### CODE REVIEW

**Comment by jjrobothamho** [comment]
@sulthan-ahmed  Change links works with no back link issues I can see so far but the continueOnEdit functionality is flaky, this my need custom implementation.

continueOnEdit appears to be true (when going through the form) for pages we have not specified it for. I'll investigate

**Comment by sulthan-ahmed** [comment]
thanks @jjrobothamho add change to only to simple ones.  

Do the continue on edit for another time

**Comment by jjrobothamho** [comment]
No problem I have removed it from non-critical questions

**Comment by jjrobothamho** [comment]
Test restarted

**Comment by sulthan-ahmed** [comment]
@jjrobothamho can you confirm this doesn't create any bugs?

**Comment by jjrobothamho** [comment]
Change functionality in standalone works as expected in local testing however there are known caveats when traversing through the form:

Clicking back button after changing an answer could allow user to change a critical question or other questions.
However the CYA page or PDF is able to cope with critical questions or any other question being changed.
Clicking continue after changing an answer may or may not allow the user to complete a few more questions before returning back to CYA page. (User will not always be sent straight back to CYA PAge after changing an answer)

**Comment by sulthan-ahmed** [comment]
@jjrobothamho let's talk about this.  We might not be able to merge it if it's flaky

**Comment by jjrobothamho** [comment]
Closing PR as not going to fulfill acceptance criteria.

**Pull request closed without merging**
