### PR TITLE
Increase resolver timeouts and increase replicas

### PR DESCRIPTION
**Pull request by Alex-Swann**

### CODE REVIEW

**Review by cmedlandho — APPROVED** [review]
lgtm

**Review by sulthan-ahmed — APPROVED** [review]
lgtm

**Comment by sulthan-ahmed** [comment]
can we close this PR @Alex-Swann ?

**Comment by Alex-Swann** [comment]
> can we close this PR @Alex-Swann ?

closed! @sulthan-ahmed

**Pull request closed without merging**
